batch_size: 128
config_file: null
data_dir: /media/makarem/Data/cifar100
device: cuda
learning_rate: 0.001
log_dir: runs
model: resnest101e
name_prefix: sam_False_rho_None_lr_0.001_06-27-17:29:17
num_epochs: 10
rho: null
use_sam: false
weight_path: /media/makarem/Data/unlearn/logs/media/makarem/Data/unlearn/logs
